
EndpointList = ["https://api.devnet.solana.com"]
KeystorePath = "./keys/solana_keys.json"

StakeManagerProgramID = "5N1PkgbPx5Qs3eGaJre16AHsNMRPYM9JSwxXDG83tWX9"
MintManagerProgramID = "HDb577JnkPHLFpfbTg1ncX9jmVHGjzX6S9bgZvNnXjVj"

RSolMintAddress = "6jnyhgA2dPWDpw1WqgTaCyjp8otXkP5655DQ6RSnwbv5"
FeeRecipientAddress = "344uJfqqsMji7jkcoGY6vcHpExsupcygpex6bJvq2ywG"
ValidatorAddress = "vgcDar2pryHvMgPkKaZfh8pQy4BJxv7SpwUG7zinWjG"
BridgeSignerAddress = "4hnrULUvAN58iUNaBLQxwVDJV4Qa1G5QGTr7aykjXra7"

FeePayerAccount = "CCD2dZ17Gse1EEadCznr94bMNyiFsEfAmywwiFuP5G34"
AdminAccount = "AcHoouLiNg8uxzwrXPSjTKEMfvDmkKpXyU9uGY61QASh"
StakeManagerAccount = "FccgufF6s9WivdfZYKsR52DWyN9fFMyELvKjyJNCeDkj"
MintManagerAccount = "5ou6pU6ByghiA148DokoVQLpPqGcnww9qS8TQzwcmQcx"

Bond = 0
Unbond = 0
Active = 0
LatestEra = 0
Rate = 1000000000
TotalRSolSupply = 0
TotalProtocolFee = 0

RateChangeLimit = 100000000 # used by rsol-set-rate-change-limit 
UnbondingDuration = 1       # used by rsol-set-unbonding-duration
UnstakeFeeCommission = 0    # used by rsol-set-unstake-fee-commission
AddValidatorAddress = ""    # used by rsol-add-validator
RemoveValidatorAddress = "" # used by rsol-remove-validator
